---
title: "Progress meetings"
---



Deliberate practice requires regular feedback. It's important to review the progress we can make in order to understand how we are performing and make adjustments as we go.

Each week, students can use [PsyBot](psybot.html) office hours and to get brief 
feedback on their work, but we use regular progress meetings to prompt a more general reflection on progress and plan for the semester ahead.


## Format

Progress meetings will:

- happen twice each semester
- include *two* or *three* students and their tutor (i.e. you and one or two other students)
- last around 30 minutes
- will be held face to face in your tutor's office


## Booking and preparation

*Students set the agenda* for these meetings.

Before the meeting, students should complete the [planning a progress meeting](tasks/growth-planning-progress-meeting.html) task.


## Recording and making minutes

For meetings to be effective, it's important to:

- record what was said, and and actions agreed and
- review progress against these actions at the next meeting

In the week after your meeting we will ask you to record the minutes of the meeting and share them with your tutor, and the other student in the meeting.


## Follow-up

Meetings are pointless if they don't lead to changes in your planning or practice.

One good way to hold yourself to account (and make sure you're making progress) is to review your progress against the actions agreed in the meeting. 

It's important to keep notes on the work you do following Progress meetings; this is something that we will review in later meetings.


## Know your tutor

Progress meetings are the main way to get to know your tutor. It's helpful for students to know their tutor for a number of reasons, but an important one is that at the end of the course your tutor will be 
in a much better position to write a reference for you if they know you well. See the task on [planning your reference](tasks/growth-planning-reference.html) for more on this.



