---
title: "Notes for staff on first stage 1 progress meeting"
---



### Week 1/2: Gentle introductory meeting, 20 mins

The purpose of this meeting is to get to know students.

Some general questions to ask:


######  Getting to know tutees

- How did you get interested in Psychology?
- Did you study Psychology A level?
- If so, which topics did you enjoy the most?


Settling in...

- Have they traveled far to come to Plymouth?
- Have the settled in, found friends in halls etc?
- Are they aware of the welcome event

University information...

- Do they have computing account and card
- Do they have access to the DLE, timetable? 
- Do they understand about workshop groups/allocations?


Expectations...

- *Tutors*: Explain what a personal tutor is for (academic and pastoral support, and a first port of call to access other university services)
- *Office hours*: Remind them about office hours and booking them via the DLE or with you individually
- *Attendance*: Explain the importance of attending monday briefings and workshops
- *Email/comms*: Explain that most university communications will be via email — this needs to be checked daily, and preferably at the start and end of each day. (Could also mention about email ettiquette)
- *Paid work*: Ask how much paid work they do. Remind them that this is a FT course and they will be expected to do around 37 hours per week, including recommended preparation and self study. 


Future directions

Do they want to be a professional psychologist? Clinical/health
/forensic?
- Are they aware of the various training pathways for them? 
- Suggest that is something to investigate during the year, mention www.prospects.ac.uk


###### Practical considerations

Briefings

- Did they attend the Briefing meeting on Monday morning at 10am on Zoom?
- If so, did they find it useful?
- If not, what prevented them? Encourage future attendance. Briefings will be an important orientation for students through the semester.


Practice

- Make sure students know about this site (<http://plymouthpsychology.github.io/practice/weekly.html>).

- Remind them these tasks are designed to be completed weekly

- PsyBot is an experimental AI tool we are trialling to give targetted feedback.

- They can upload work to <http://psybot.llemma.net> to get formative feedback on these tasks (and others in future).


Progress meetings

- Mention that next meeting will be in week 5/6
- Students will need to set the agenda for it, and make notes from it
- There is a practice task which covers this


###### Learning about students' choice of Plymouth

As a school we are also very interested to hear from students on these topics:

Why Plymouth? 

- Was there anything special about the place?
- Was there anything special about the university?
- Was there anything special about the course?

Open/applicant days?

- What did you like about them?
- Do you have any suggestions for improvements? 
- What aspect of your degree are you most excited about? 




